baseURL = ''
languageCode = 'ja'
title = '農工大 IEEE SB 10周年記念イベント'
theme = "beautifulhugo"
enableGitInfo = true

[Params]
socialShare = true

[Author]
email = "tuatieeesb@gmail.com"
twitter = "@TIeeesb"

[markup.goldmark.renderer]
unsafe = true
